apiVersion: v1
kind: Pod
metadata:
  name: housing-app
  labels:
    app: housing
spec:
  restartPolicy: Never
  containers:
    - name: housing-app-container
      image: fsds/housing-repo
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
      command: ["python", "main.py"]
